import type { Metadata } from "next";
import "./globals.css";
import "./features/tiles-gallery/styles.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import GlobalProviders from "@/app/GlobalProviders";
import { futura } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${futura.variable} antialiased`}
      >
        <GlobalProviders>
            {children}
        </GlobalProviders>
      </body>
    </html>
  );
}
