import type { Metadata } from "next";
import { Jost} from 'next/font/google';
import "./globals.css";
import GlobalProviders from "@/app/GlobalProviders";
import { ReactNode } from "react";
import BackToTopButton from "@/app/components/BackToTopButton";


const jost = Jost({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-jost',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="de" className={`${jost.className} antialiased`}>
      <body>
        <GlobalProviders>
            {children}
            <BackToTopButton />
        </GlobalProviders>
      </body>
    </html>
  );
}
